# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Prepare
      run: mvn install:install-file -Dfile=br.usp.each.saeg.jaguar.core/lib/org.jacoco.core-0.7.6.jar -DgroupId=br.usp.each.saeg -DartifactId=org.jacoco.core -Dversion=0.7.6 -Dpackaging=jar
    - name: Build
      run: mvn clean install
    - name: jaguarportal-submit
      # You may pin to the exact commit or the version.
      # uses: ericksonlbs/jaguarportal-submit@e749a1f066dd50ef76ac3bc163df650dc6cec7aa
      uses: ericksonlbs/jaguarportal-submit@v0.0.1-snapshot
      if: failure()
      with:
        # The key of the Jaguar Portal project
        jaguarPortalProjectKey: JaguarIMC
        # The name of the Jaguar Portal project
        jaguarPortalProjectName: "Jaguar IMC"
        # The Jaguar Portal server URL
        jaguarPortalHostUrl: https://jaguarportal-api.azurewebsites.net
        # The APIKey from Jaguar Portal
        jaguarPortalAPIKey:  ${{ secrets.jaguarPortalAPIKey }}
        # The analisys path
        jaguarPortalAnalisysPath: /br.usp.each.saeg.jaguar.example/.jaguar
        # The classes path
        jaguarPortalSourcePath: /br.usp.each.saeg.jaguar.example/src/main/java        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: jaguar
        path: br.usp.each.saeg.jaguar.example/.jaguar
        retention-days: 5
